#dev configurations
env: dev
routes:
  gateway: http://localhost:8080
#  auth: http://localhost:8081
  identities: http://localhost:8082
  documents: http://localhost:8083
  audit: http://localhost:8084
  projects: http://localhost:8085
  incident: http://localhost:8899

server:
  gateway:
    port: 8080
#  auth:
#    port: 8081
  identities:
    port: 8082
  documents:
    port: 8083
  audit:
    port: 8084
  projects:
    port: 8085
  incidents:
    port: 8899

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/psw_dev
    username: psw_app
    password: ${DEV_USER_DB_PASSWORD}
  flyway:
    enabled: true
  cloud:
    openfeign:
      okhttp:
        enabled: true

app:
  security:
    cors:
      allowed-origins:
        - "http://localhost:5173"
